name: ci-ubuntu

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CODECOV_TOKEN: 'a6611bcf-89ee-410d-acfa-d4f130b31365'
jobs:
  call:
    name: Call spack reusable workflow
    uses: LIHPC-Computational-Geometry/lihpccg-ci/.github/workflows/spack-reusable.yml@fix_testlink_pytest
